language: python
matrix:
  include:
  - env: TARGET=python36
  - env: TARGET=python37
sudo: required
services:
- docker
before_install:
- true
install:
- docker build . -t ${TARGET} -f .travis/${TARGET}.docker
before_script:
- true
script:
- true
deploy:
  provider: pypi
  user: sperkins
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  password:
    secure: XWHWVt4eNVA58hNaKvWFIdvVQcdeG/nNHcx9edfqwCrl+qJP1S9J/NeMY7M3iBXBOeyjeFXcdZpB+4IeeazC4X8JV/oTI4e92YkshxjTeexEHh4iTMdzfl7g6Im/1zyhLTDDbpttFtEIgDLbq4aITBlu3pC7PlU+j6eQU9ejkShyIpnRBKj2pVxm3AfdqBgsyotwhQQBvEyoFq2r3uRp+fHqPmyKiKh8X+RNg5MJ/42GlJdReVW6kNPVSHRqj6fom/0B76H11lnSgbzf9wBygKwfzQ6PAZNW9GKBt+7wi7P3ubnFrsiJ+GVWhnCIDcDEk9cDNEh/bQwi56fpHhWr8a3lx26byGirnSKIWjO+K6khZM+Qqz8JvhtiEb8uWODRiKd3jFgW7zk6mrXnUpt/hS//38IeasNWESp+05EVqQmeVbWNL3slaHxTw7PTUEyQ1e4t8qpFFbwAj8IF9hDk7WW47iWKTs9tt73bZe0+2Qz0P1O1onewXvRVvsAn/dNQrvgArWWkZTgneuoTG3t70yKnDr1jC05YHaBDgA4JdqtzLByrv8dTb9PdacpAgymqsGxYRRRbcHIkfBKyngbxjILeSzVQnHxbLRbESvDAliZTxMCNiJY5wX0Oj1vNmOiGDek3x9q6Pjpc5NoUZVoixCxiXtQHpPuJEnO1CScKZoM=
  on:
    tags: true
    branch: master
    repo: ska-sa/xova
    python: 3.6
